### ISSUE TITLE
Missing support for arm64 & i386 architectures

### ISSUE THREAD

**Issue by borut-t** [PayPal-Mobile/ios-here-sdk-dist#101]
After installing sdk with cocoapods the project build on Xcode 8, swift 3 fails with error:

```
clang: warning: libstdc++ is deprecated; move to libc++
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CLLocationManager", referenced from:
      objc-class-ref in PayPalHereSDK(PPHLocationManager.o)
      l_OBJC_$_CATEGORY_CLLocationManager_$_PPH in PayPalHereSDK(PPHLocationManager.o)
  "_kCLLocationAccuracyThreeKilometers", referenced from:
      -[PPHLocationManager initializeCLLocationManager] in PayPalHereSDK(PPHLocationManager.o)
ld: symbol(s) not found for architecture i386
```

It looks like it cannot run on simulator (i386 architecture) and/or on device 64-bit architecture. Is that correct?
Is there a way to build i386/arm-64 binaries?

**Comment by ppmtscory** [comment]
@borut-t I'm going to close this out per our conversation.  The issue had to do with the podfile being used and the way everything was being loaded.

**Comment by thuydao** [comment]
@borut-t : You can fix this problem by add 'CoreLocation' to project:
Go to: Project> Build phases > Link Binary With Libraries> select '+' > add CoreLocation.Framewor.
This work for me!

**Comment by borut-t** [comment]
@thuydao already did that.
