### ISSUE TITLE
4 headers in SDK have missing newlines at end of file

### ISSUE THREAD

**Issue by ChristoDeluxe** [PayPal-Mobile/ios-here-sdk-dist#27]
4 header files in the closed-source PayPalHereSDK.framework are missing newlines at the end of the file.  This results in warnings or errors in some build situations.  Please add a newline to those files when you next revise the framework.

The files are:
PPHCardNotPresentData.h
PPHChipAndPinEvent.h
PPHInvoiceProtocol.h
PPHLoggingDelegate.h

I'd make a PR, but you probably need to correct those files in your private repo for the SDK...

**Comment by ppmtscory** [comment]
Thanks @ChristoDeluxe - we'll have somebody take a look at this.

**Comment by mpavlinsky** [comment]
I've submitted a pull request for this. Future SDK releases should be more friendly for partners that have the "Missing Newline At End Of File" warning enabled.
