### ISSUE TITLE
ios validation issue

### ISSUE THREAD

**Issue by achyutrk** [PayPal-Mobile/ios-here-sdk-dist#32]
Hi Guys,

My app builds properly but when i try to validate I get the attached warning from app store. I think this will reject the application. If you could please help me with PayPal here SDK. I have used the latest SDK. I get error with "deepcopy"

After removing PayPal SDK validation error was fixed so it was something related to PayPal.

![paypal_error_private_selector](https://cloud.githubusercontent.com/assets/12947322/8225084/d3a77f2e-15ad-11e5-876c-a6101418b2be.png)

Regards,
Achyut

**Comment by ppmtscory** [comment]
Do you have the '-ObjC' linker flag set?  In Xcode it's under your app in build settings > linking > other linker flags.  The flag that needs to be added is "-ObjC".

**Comment by jaredegan** [comment]
The SDK uses an NSDictionary extension that has a `deepCopy` method. I don't think adding `-ObjC` will do anything about this warning. It's coming from Apple's App Store submission process, not from Xcode's compilation.

That being said, this is a false positive. We're not actually using whatever non-public selector the validation warns about. It's just a category method that is named the same. I have submitted apps with false positives warnings of the same sort for the past couple years without issue.

My recommendation:

- @achyutrk: just submit the app. I believe it will be fine, let us know if it's actually rejected.
- SDK team: We should rename that category method to avoid this confusion in the future.

**Comment by ppmtscory** [comment]
Thanks @jaredegan.  I'm going to close this issue now but please let us know if your app submission is rejected due to this particular warning.
