### ISSUE TITLE
Paypal Here Integration - Wrong screen displayed

### ISSUE THREAD

**Issue by jforjava1981** [PayPal-Mobile/ios-here-sdk-dist#37]
I am trying to integrate Paypal here. For that I want to allow to activate merchants on my backend web application. For this I have been following ios sdk docs and specifically onboarding guide to do this. I am also referring to REST api reference of Paypal. I am so far successful up to a stage where I am able to retrieve the authorization code and get initial access_token,refresh_token using the authorization code. Now the real issue is that when I /merchant is trying to give third party permissions,  the appropriate screen as shown in guide/docs is never shown. It only rarely shows up only if I manually login to sandbox account and then start onboarding flow. the screen I get instead is attached here : 
![problem_paypal](https://cloud.githubusercontent.com/assets/5867866/8711321/713fa9d4-2b6e-11e5-8be7-57b21807a492.png)

Why is this so? I am testing it using sandbox account : 
Various URLS I am using for testing :
1) To submit business/merchant information to start onboarding :
https://www.sandbox.paypal.com/signup-pph
https://www.sandbox.paypal.com/webapps/mobilemerchant/page/mpa/ob/geturl?onbver=2.0&country.x=US
both above work. not sure which one will always work and why there are two?

2) To request the Auth Code and give third party permissions:
https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize
When I redirect to this URL it doesn't show the correct page. Why?

3) To get access token  :
https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice
this worked,however in REST API reference docs where this URL is mentioned it asks  to pass redirect_uri as a parameter which gives wrong response specifically : redirect_uri mimatch between auth code and token
As per paypal here SDK and onboarding guide following url should be used but it times out
https://api.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice

I have pointed many issues in one single Issue however major issue is flow doesn't follow correct steps and screens which confuses the user.

Also I am yet to test the APIs by using access_token.Not sure which urls to follow?

**Comment by ppmtscory** [comment]
@jforjava1981 This is the first image that's seen as it's recognizing the login from the previous "signup" page so that the customer doesn't need to login to their account a second time in the same flow.  Once they click "Continue" then they will see a list of the permissions that you are requesting.  The screen with the scopes is the only one outlined in the Guide to show what it would look like.

To answer your other questions:
1) I recommend using https://www.sandbox.paypal.com/signup-pph with the form post.  The other link is fine as well, it just simplifies things within the sandbox by putting the parameters as a query string instead of a form post.
2) I believe this is answered in the first question of your post.
3) This /tokenservice URL that's called out in the Onboarding guide should not need a redirect_uri as part of the request.  The request is outlined in the guide (and below) and as long as all the parameters are accurate, there shouldn't be a timeout.
```
curl https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice \ 
-u "<Client-Id>:<Secret>" \
-d "grant_type=authorization_code&code=<Authorization Code>"
```

**Comment by jforjava1981** [comment]
Ok. But regarding the image ..As per your opinion that the permission listing image is displayed after the image I have attached. However when I click on continue on the image I attached paypal shows a box which says "Verifying information.." and immediately redirects to my site. It never really shows any permission listing even though i have enabled email and address scopes along with paypal here and login with paypal for my app on my developer site. 

please advise why i dont see the permission listing page?

**Comment by ppmtscory** [comment]
@jforjava1981 you will only see the permissions the first time that you grant them.  If you login with an account that's already granted permissions, then they will skip that page and just be redirected.

**Comment by jforjava1981** [comment]
@ppmtscory Sorry for asking the question again for question  number 3) REST API reference has URL :
https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice

and guide has URL : 
https://api.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice

So for live transaction testing which one I should use : 
https://api.paypal.com/v1/identity/openidconnect/tokenservice
OR 
https://api.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice 

please advise.

**Comment by ppmtscory** [comment]
@jforjava1981 Either should work so just use the one from the Merchant Onboarding guide for consistency.
