### ISSUE TITLE
Paypal getting new Access token from refresh token doesn't work

### ISSUE THREAD

**Issue by jforjava1981** [PayPal-Mobile/ios-here-sdk-dist#38]
Hi,
this is the second issue I am facing with Paypal Here integration. When I got initial access token I got a refresh token as well. However when I try to get new access token using the refresh token I initially received I either get request timeout or response which says 500-Internal Server error.

I will give how I am trying to fire URLS using CURL util  before I try it using in actual code. Rather I have imlemented it but as it gives 400 bad request I am trying with CURL util and here is what I get : 
 Case 1) URL :
               https://api.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice
               Parameters :
              i) for authorization : Base64 encoded string of the format clientId:secret
             ii) scope : URL encoded string of scopes as given in onboarding guide. value of this 
                             parameter  same as the scope parameter value I send during initial access token 
                             request.
            iii) grant_type: value I send is refresh_token
            iv) refresh_token:value of refresh token I initially got from Paypal.
           
  Response I get : In this case I get request timeout. and connection closes with connection reset with peer.

Case 2) URL :
               https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice
               Parameters :
              i) for authorization : Base64 encoded string of the format clientId:secret
             ii) scope : URL encoded string of scopes as given in onboarding guide. value of this 
                             parameter  same as the scope parameter value I send during initial access token 
                             request.
            iii) grant_type: value I send is refresh_token
            iv) refresh_token:value of refresh token I initially got from Paypal.
 
Response I get : Here I get following response:
{"error_description":"POST /v1/oauth2/token returned a response status of 500 Internal Server Error","error":"500","correlation_id":"f30f09cc131ee","information_link":"https://developer.paypal.com/docs/api/#errors"} 
Closing connection 0

Whats wrong with this ? I am testing on sandbox environment. I also tried dropping scope parameter in both requests but the result is same. 

 Please help as I am unable to move forward with integration.

**Comment by ppmtscory** [comment]
@jforjava1981 can you validate that your curl request looks like this?
```
curl -v 'https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice' \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -H "Authorization: Basic QVZpa2hibHhqR................zFYaDh0TzA5ak9CTlNkZXBGTnA=" \
    -d 'grant_type=refresh_token&refresh_token=0EZdA1nWXIXcU..........S2_EtWpzOSbaY4g'
```

**Comment by jforjava1981** [comment]
This is strange now...Please find below my request formatted accourding to your format:

curl -v https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice -H "Content-Type: application/x-www-form-urlencoded" -H  "Authorization: Bas
ic  AXMK4HhrTAJGcjKWFpiwqs3gtYhn_glZaM0uNs60aHMy7Po81YWK1oBWVEMuSF4Zfl5tvt-EmHcnwGjl:EL_WLvEInLTRlmJp7ZqhABPXCNAnUlF0it4MVeKlNdkSRpm1gkl3ZOu5MUMR9hZ6PqXwdTo-48Q153XC" -d 'grant_type=refresh_token&refresh_token=RccCjmIFnRE3W5BKJdONWeHsUZCx_mXgUCIhIEKIH_AWjExn6SStHZmlJ8eRDkNxA5RUzJzDsFWF4HWy5i3jcZAfDNAofsZLQKC4wOPRcpd09Nqp52_QHdJ5V6k'

I know this is wrong to share the secrets here but these are test accounts and its ok.

However I get following response : 
{"error_description":"client id or secret is null","error":"invalid_client","correlation_id":"0ab038b3afc39","information_link":"https://developer.paypal.com/docs/api/#errors"}. 

This is not possible as this clientId and secret are still there on my developer account. How come they can be invalid. Rather as a workaround for testing I am continuously adding a new sandbox test account for merchant and activate to get new access token as refresh doesn't work. If client is invalid how come new access token gets generated. Can you please advise?

**Comment by jforjava1981** [comment]
Also eralier request(mentioned in original post ) had simiar headers attached by curl by default.So everything was same its just that I explicitly added content type header and Authorization:Basic header instead of using -u option which actually did the same thing and added Authorization header automatically.

**Comment by jforjava1981** [comment]
Please let me know if you can have a quick skype call as this is a major bloker for upgradint to test server from our dev sever.

**Comment by jforjava1981** [comment]
Well Somehow I resolved the error "CliendId or secret is null : ivalid client by base64 encoding the entire string "{client_id}:{secret}"  and setting it as part of Authorization header. however I get follwoing response like posted in original post:

{"error_description":"POST /v1/oauth2/token returned a response status of 500 Internal Server Error","error":"500","correlation_id":"2b789ba392b56","information_link":"https://developer.paypal.com/
docs/api/#errors"}* Closing connection 0

Please help me out

**Comment by ppmtscory** [comment]
It actually looks like a previously closed account with the same email address may be causing a conflict.  Can you please go to developer.paypal.com, create a new app that's tied to a different email address than the one you currently have tied to that client ID, and then try the full onboarding flow again?  This should allow you to use different client ID/Secret as well as brand new refresh token for your test merchant.  There indication in the logs on our end that this may be the case.  Also, I'm unable to reproduce it and that is one of the differences between your tests and mine.

**Comment by jforjava1981** [comment]
OK.let me do that and get back with results.

Thanks,
Shailesh

**Comment by jforjava1981** [comment]
Hi Cory,

        Nothing worked. So Just to take a chance I changed the URL from
 https://api.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice
to 
https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice

And it worked. However I was using  URL https://api.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice
as suggested by you in earlier issue I raised in this forum.
to do everything (1. getting initial access token 2. refresh token)

the sandbox environment is really giving lot of trouble as not one URL consistently works for   both getting token and for gettting refresh URL.  

Please advise.

**Comment by jforjava1981** [comment]
I have another question. When I sent sope value : openid email address https://uri.paypal.com/services/paypalhere https://uri.paypal.com/services/paypalattributes/business it gave me invalid scope error with URL https://api.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice, when I tried to retrieve the code. I had enabled corresponding scopes on my sandbox account. Does it take 3 hours to  update this information as well?

**Comment by ppmtscory** [comment]
I'm not sure why you are having so many issues with the URLs as I'm able to use either one to generate an access token from a refresh token.  Either way, continue to use the one that works for you.  For your latest questions, I believe it's good practice to include the general openid scope along with the other scopes.  The Address Information section underneath the Log In with PayPal section would contain both the email address and address fields for those respective scopes.  Unfortunately there is a 3 hr app cache refresh so if you change a setting, it can possibly take 3 hours to be reflected.

**Comment by jforjava1981** [comment]
Hi Cory,

 I am not able to understand why the URL and request which works at one point of times starts breaking after some time. this is really affecting my client's buinsess to launch the paypal Here integration.

 Here is the latest update on the request I am making to refresh token: 

{"error_description":"Unable to refresh access token","error":"invalid_request","correlation_id":"842b6123bc302","information_link":"https://developer.paypal.com/docs/api/#errors"}* Closing connect

Here is my request :

curl -v https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice -u AfRI_HaBN1swLyO7xGDpSuNAXAPbb6W0k-ONM378wCEl02LvgqcTuA88p4xJ1rAa9SGh4iwOfir3hcbW:EFK1LiItly0FZh-CBVVx03ICpEOHwbB0XLW2BQCKEZsfAYsgVI3d7mJPku4jzwtxZAePRT_KuWBq-E-M
 -d "grant_type=refresh_token&scope=https%3A%2F%2Furi.paypal.com%2Fservices%2Fpaypalhere+email+address+https%3A%2F%2Furi.paypal.com%2Fservices%2Fpaypalattributes%2Fbusiness&refresh_token=O7ak9yeUx5l2mVrpTUigHlWsHqjTzetntrBwfDrKRcSs28Anr8WdYG-llLhOzbw-VQfbkd-vam-IxcjGjEOZZC_0I6d30vO3rIv4ZBvs9NCwnJ1BUTuIOdleUv8"


Can you please help asap.

Thanks,
Shailesh.

**Comment by jforjava1981** [comment]
and https://api.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/tokenservice URL still gives timeout error

**Comment by ppmtscory** [comment]
@jforjava1981 First off, you don't need to specify scopes when exchanging a refresh token for an access token.  Secondly, that request is failing because it's trying to generate an access token from an account that's been closed.  You'll want to purge that refresh token and either go through the onboarding again with a different merchant account or you'll need to test with a different refresh token that's tied to an active account.

**Comment by jforjava1981** [comment]
Hi Cory,

I am sending this request with new merchant sandbox account only created afresh as you earlier pointed out. When this happened last time, I created the new merchant and did on boarding process again for that merchant. Why is it closed ?  It's still active there on my developer account. My developer account is shaileshinpune123@gmail.com. sandbox account is test4@martianmart.com. I don't understand why the merchant account that I add on my developer account gets closed automatically. Where I can verify the account is closed?  Is there a validity period for sandbox test accounts? I have in fact generated the new clientid and secret by adding new app.Can you please help answering the questions I have posted here?

**Comment by jforjava1981** [comment]
I am still able to login to sandbox site with test4@martianmart.com. is this possible if its closed?

**Comment by jforjava1981** [comment]
I have no problems to add a new merchant and redo the on boarding again but what will guarantee that it will not be closed automatically? is there something in my hand to prevent that?

**Comment by jforjava1981** [comment]
This lets me down in front of my client as I do all the testing here on local and everything works fine with new merchant and new app I add and when I deploy that to our test server nothing works especially refresh token functionality. This is really getting ,my client pissed off as this happened twice.

**Comment by ppmtscory** [comment]
@jforjava1981 your account test4@martianmart.com is still fine, open, and active.  The 'merchant' account (the one you put through the onboarding and generated a code/refresh/access token for) was closed.  Therefore, since the account was closed, you were no longer able to generate an access token from that refresh token.  Your test4@martianmart.com account is your 'Partner' account.  That's the account that's tied to your App and credentials on developer.paypal.com and processes the calls on behalf of the 'merchant' account.  This account is fine.  You need to go through onboarding again with another 'merchant' account to generate the proper tokens.  The 'merchant' account is the account that gives permissions to your 'Partner' account as well as receives the funds from the payments.  Once you have those tokens, then as long as that 'merchant' account stays open, then you should be fine.

**Comment by jforjava1981** [comment]
Ok Maybe I confused the account. But as you explain the merchant account I am using is test6@martianmart.com. Is this closed. I am able to login to sandbox account with this merchant.

**Comment by jforjava1981** [comment]
This is what I got in notification on 26 July. and for this merchant the refresh token functionality was working fine which is now not working.

Hello Roger Federer,

Your email is confirmed. Now that you’ve got PayPal you can easily offer your customers one-time payments, pay-as-you-go and subscriptions.
https://www.sandbox.paypal.com/us/cgi-bin/?cmd=_accountsetup-ppbasics

Starting to receive payments? Make sure your account is ready.
https://www.sandbox.paypal.com/webapps/mpp/merchant-welcome

Questions about your account? Contact us.
https://www.sandbox.paypal.com/us/cgi-%20bin/helpscr?cmd=_help&t=escalateTab
 
----------------------------------------------------------------------
Help
https://www.sandbox.paypal.com/webapps/helpcenter/home/

Security and Protection
https://www.sandbox.paypal.com/webapps/mpp/paypal-safety-and-security
This email was sent by an automated system, so if you reply, nobody will see it. To get in touch with us, log in to your account and click "Contact Us" at the bottom of any page.

Copyright © 2015 PayPal, Inc. All rights reserved. PayPal is located at 2211 N. First St., San Jose, CA 95131.
  
PayPal Email ID  PP1811 - 15b2ce2ce4ad2

**Comment by jforjava1981** [comment]
Ok seems to be working. Let me confirm again after working with it for a couple of times.

**Comment by GurvinderParas** [comment]
Not getting access token Using Refresh token gives error client id or secret is null

Any Solution!

**Comment by ppmtscory** [comment]
@GurvinderParas please file a ticket at www.paypal-techsupport.com/app/ask with the account information that you're using and we'll have somebody take a look.  Please provide the request/response showing the error with correlation ID.

**Comment by GurvinderParas** [comment]
I already done this. But I never get any response.

**Comment by ppmtscory** [comment]
Can you let me know the ticket number so that I can make sure somebody has a look?
