### ISSUE TITLE
Swipe Issue w/ New Phonegap Plugin We Built for PayPal Here

### ISSUE THREAD

**Issue by swire** [PayPal-Mobile/ios-here-sdk-dist#42]
We have built a plugin for phonegap for the PayPal Here SDK and have everything nearly working. The only issue that remains is swipe. 

When we send a test transaction, it's not making it through for swipe. It is for keyed entry though. We're not sure if it's the plugin or if it's something on PayPal's end. 

Alex and Brian, please post specifics for this issue to be addressed.

**Comment by bcgood** [comment]
We're having trouble passing the swiped card info to make a PayPal payment from our end. Seems like a method in our PayPalHerePlugin.m file is not returning anything to the App which is the successHandler for PayPal's method for processing payment. The theory so far might be our callback is expiring but we're still looking into it.

@AlexGamezo will be expounding on it soon, with code, as he has the most knowledge being the one working closely on it.

**Comment by ppmtscory** [comment]
Thank you for creating a plugin!  Please do keep us posted if you think there's an issue within the SDK.

**Comment by swire** [comment]
We were able to resolve the issue tonight and have the new plugin working :)

**Comment by nanduahmed** [comment]
Hi Swire,

Do you have this plugin availaible somewhere. I am looking forward to integrate it.

**Comment by nanduahmed** [comment]
@swire is this plugin commited somewhere in repository ?

**Comment by bcgood** [comment]
@nanduahmed thanks for your interest, it is currently in a private repo until at least after our app gets approved by apple

**Comment by nanduahmed** [comment]
@bcgood Thanks. Hope it will be available soon. Please notify

**Comment by nanduahmed** [comment]
I am just trying to implement the cordova plugin since it is a critical need. Could you please share some details how can I get the swipe events using cordova on html page.

**Comment by si458** [comment]
sorry to update an old issue, 
but was the any update on a PayPalHERE SDK for Phonegap/Cordova?

**Comment by rocksmusic20** [comment]
Hi, is that plugin available?
