### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by gpradeep** [PayPal-Mobile/ios-here-sdk-dist#44]
I created a sandbox test user and successfully logged in through browser.(https://www.sandbox.paypal.com/)
But when i tried same thing in sample app I was unable to login
Can you please help me on this

**Comment by ppmtscory** [comment]
Are you trying to login on the very first screen that also asks you to choose your server (sandbox, live, stage)?  If so, then that's a login for the sample heroku server that the App uses.  The default user is 'teashop' and the default password should pre-populate.  If that doesn't work, for whatever reason, then I've created you a username: gpradeep and your password is 8, 1's (11111111).  Once you get past this login, then the next login will be where you enter your sandbox account credentials.

**Comment by gpradeep** [comment]
Thank you very much.
