### ISSUE TITLE
iOS 9 / iPhone 6 - Bitcode Error

### ISSUE THREAD

**Issue by cesariel** [PayPal-Mobile/ios-here-sdk-dist#52]
<img width="783" alt="screen shot 2015-09-22 at 1 44 02 am" src="https://cloud.githubusercontent.com/assets/13699157/10026014/62946826-612d-11e5-9d72-ccd9d45273cb.png">

**Comment by mpavlinsky** [comment]
Current SDK binaries are not built with bitcode enabled. We will be enabling this soon. For the time being please disable bitcode for your application.

**Comment by cesariel** [comment]
@mpavlinsky Perfect!

**Comment by cesariel** [comment]
@mpavlinsky Maybe you could help me on this one https://github.com/paypal/paypal-retail-node/issues/1#issuecomment-143256879

**Comment by Zyphrax** [comment]
This is still an issue.
