### ISSUE TITLE
EMV reader updateRequired not set for update check

### ISSUE THREAD

**Issue by sammcewan** [PayPal-Mobile/ios-here-sdk-dist#54]
There needs to be a better way to handle this. The code from the example app is as follows.

```
- (void)checkForSoftwareUpgrade {
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        if ([self updateRequired]) {
            [self beginReaderUpdate];
        } else {
            [self displayReaderStatusWithMessage:@"Ready To Transact" successfulStatus:YES];
        }
    });
}
```

This delay is not sufficient to detect some updates and consequently the reader gets stuck in a position where we cannot transact without changing the code to being ~5 seconds.

There should be a callback or preferable a block once the device determines an update is available or not as adding a 5 second delay is not acceptable on our end.

**Comment by mpavlinsky** [comment]
I will update the TakePayment app with code that is better suited to detect update.

Generally the approach should be to check inside the `didReceiveCardReaderMetadata` delegate method.

**Comment by mpavlinsky** [comment]
TakePayment app is updated in release-1.6 to have a more robust check.
