### ISSUE TITLE
Microphone not detected in "Take Payment"

### ISSUE THREAD

**Issue by sammcewan** [PayPal-Mobile/ios-here-sdk-dist#55]
Latest take payment is not detecting magstripe reader. Microphone not requested, audio not pumped, nothing in debug logs. Tested on two devices with different headphone jack readers. 

Also tested with previous versions of take payment with success.

**Comment by ppmtscory** [comment]
@sammcewan I can run some tests to check on this as soon as my Xcode is done updating.....

**Comment by mpavlinsky** [comment]
I'm not seeing this issue. Can you try deleting the app, cleaning and rebuilding? Or perhaps it's an account permissions issue? Does this only happen in a single region or is this the behavior for accounts in multiple regions?

**Comment by ppmtscory** [comment]
Closing this issue as I believe, from other conversations, it has been resolved.
