### ISSUE TITLE
Support for Tap and Go contactless reader

### ISSUE THREAD

**Issue by jarred-s** [PayPal-Mobile/ios-here-sdk-dist#56]
I am attempting to develop an application for the new PayPal Here Tap and Go reader recently released in Australia and the UK for contactless payments.

https://www.paypal.com/au/webapps/mpp/accept-mobile-payments

Does the current SDK support this reader through the EMV interface and if not will this be included in the near future?

**Comment by djMax** [comment]
Use the release-1.6 branch. It will get merged into master in a week or so.
