### ISSUE TITLE
[1.6] Q: What if getCurrentNavigationController returns nil?

### ISSUE THREAD

**Issue by rleiwang** [PayPal-Mobile/ios-here-sdk-dist#61]
I use react native Javascript Navigator to manage the screen stack. What happens if getCurrentNavigationController returns nil. Can the screen show up? 

```
/*!
 * Mandatory if you are using the EMVSDK. Returns a reference to a
 * navigation controller we drive UI off of.
 */
- (UINavigationController *)getCurrentNavigationController;
```

**Comment by mpavlinsky** [comment]
We do not currently support attempting to present on a nil UINavigationController.

**Comment by rleiwang** [comment]
@mpavlinsky got it. Thanks
