### ISSUE TITLE
[1.6] How to display card reader status

### ISSUE THREAD

**Issue by rleiwang** [PayPal-Mobile/ios-here-sdk-dist#63]
I am using processPaymentUsingUIWithPaymentType for card process. As it processes, it displays "Processing" in the middle of the screen, I want to do something similar to show card reader status. Can someone shed some light on how to do it? What SDK uses to display "processing" bar?

**Comment by ppmtscory** [comment]
@rleiwang you can just use the standard spinner via [UIActivityIndicatorView](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIActivityIndicatorView_Class/).
