### ISSUE TITLE
CHIP Reader Software Update process fails

### ISSUE THREAD

**Issue by AlexGamezo** [PayPal-Mobile/ios-here-sdk-dist#66]
The card reader states that "Software Update Required" when I connect it to my app. I've attempted to use the "beginUpgradeUsingSDKUIForReader" method to initiate update, but each time the UI displays in app, then updates reader stating "Downloading files", followed quickly by "Software Update Failed" and the error message for the callback states that the SDK "Failed to verify reader"

In making the call out for upgrade, I pass in "activeReader" as description of what reader to update. Is there something wrong with that, or any additional information I need to pass?

**Comment by ppmtscory** [comment]
Are there any errors or anything present in the console logs when this happens?

**Comment by AlexGamezo** [comment]
Thank you for your assistance!

Looks like the errors I'm getting are SSL errors, handshake failures and HTTP load failures.
Is there any additional configuration I must make for the SSL connection to succeed from the app?

I'll take a look at the sample, in case I'm missing something small.

**Comment by ppmtscory** [comment]
I was wondering if ATS was going to have something to do with this.  Let me discuss this, along with the looping, internally here and we'll get back to you.

**Comment by AlexGamezo** [comment]
I've attempted to perform the upgrade through the TakePayment sample app, and that fails as well. Seems to either be a reader issue (hoping not) or something a little more universal? Any luck on your end?

**Comment by ppmtscory** [comment]
@AlexGamezo can you try a system restore on the device and then reconnecting it?  To do the restore, there's a pin hole next to the power button that you press to get the restore options.

**Comment by AlexGamezo** [comment]
I've tried both a system restore and a factory reset. No dice, same result. Neither the TakePayment Sample app, nor our app is able to complete the update.

**Comment by mpavlinsky** [comment]
@AlexGamezo I tried this using TakePayment and an iOS 9.1 and the update completed successfully.

What version of iOS are you using? Have you tried multiple differently versioned devices?

**Comment by AlexGamezo** [comment]
I've only tried on one device, only one reader so far, I'll try another device shortly. Just need to get approved for my paypal business account and can try with the actual PayPal Here app as well. Does the account need to be approved for transactions in order to do the device upgrade?

**Comment by mpavlinsky** [comment]
Yes I believe you must have a current business account to get through login to the point where reader version is checked and updated.

After looking into the ATS error more it seems like it is impossible for me to package the proper exception with the PPHSDK framework. I am trying to sort out the endpoint that is causing issues, but in the meantime it looks like the app will have to add the ATS exception itself. If you want a more precise exception that doesn't shut off ATS altogether then I recommend the following in your plist:
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>paypal.com</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
		</dict>
	</dict>
```

**Comment by rleiwang** [comment]
I've got the same error message "Install software failed". I am using SDK 1.6 on ipad mini running 9.2

any advise how to fix it?

```
2016-01-07 19:56:30.514 [333:42953] 03:56:29.0551 <NSThread: 0x12cd74160>{number = 5, name = (null)} | PayPalHere: 

--- _OBSCURO_EMFJSONResponse https://www.sandbox.paypal.com/webapps/hereapi/merchant/v1/cardReaderDevice/MIURA/M010/keys



Headers: {

  "Server" : "Apache",

  "Set-Cookie" : "SPARTAJSESSIONID=cf536deaf79cb; Domain=.paypal.com; Path=\/; Secure; HttpOnly, SPARTAJSESSIONID=f9d052fafab81; Domain=.paypal.com; Path=\/; Secure; HttpOnly, SPARTAJSESSIONIDV2=MG9bChnAhKWd7j7WAGX1gbVuAeXJTEf3TR8J.1o7noxJsa22k3vOT-2vmoqyI-l0ecGftpgafEzHOZPSJakb94f42-FdEHI2oh2pcNbny0Xz7foI-Nwlxg; Domain=.paypal.com; Path=\/; Secure; HttpOnly, X-PP-SILOVER=name%3DSANDBOX3.WEB.1%26silo_version%3D880%26app%3Dhereapispartaweb%26TIME%3D1832095574; domain=.paypal.com; path=\/; Secure; HttpOnly, X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT",

  "Paypal-Debug-Id" : "13b564f4676e3",

  "Strict-Transport-Security" : "max-age=14400",

  "Content-Type" : "application\/json;charset=utf-8",

  "Date" : "Fri, 08 Jan 2016 03:56:29 GMT",

  "Content-Length" : "143",

  "X-Cnection" : "close",

  "Content-Encoding" : "gzip",

  "Vary" : "Accept-Encoding,Authorization"

}



Error: (null)



Data: {"correlationId":"13b564f4676e3","errorCode":600000,"message":"MobileMerchantPaymentServ: Unknown Error Code: 506713","errorType":"service_error"}

2016-01-07 19:56:30.517[333:42953] 03:56:29.0552      Main thread | PayPalHere: PPHBondReaderDelegate::updateFailedWithMessage : message : PPH_Software_Update_FailedToFetchEncryptionKeys
```

**Comment by ppmtscory** [comment]
@rleiwang you are getting the issue because you have it pointing to the Sandbox environment and the EMV readers do not work with the Sandbox environment.  You need to point to Production to use the EMV readers.

@AlexGamezo were you able to get yours updated, or your Prod account approved for PPH to test with the PPH App, or both?  Do you need any further assistance?

**Comment by rleiwang** [comment]
@ppmtscory Thanks for the reply. To test with EMV reader with production env, do I need do any thing extra?

You mentioned account approval for PPH testing? Do I need to do that?

**Comment by ppmtscory** [comment]
You will need a Live Business account that is approved for PayPal Here.  This would be the account that is used as the 'merchant' in the SDK and is receiving the funds.

**Comment by rleiwang** [comment]
@ppmtscory  Thanks for the info. This is to confirm it works for me in production env.

I wonder why EMV reader can't work in the sandbox env?

The other question I have is: when will 1.6.1 uploaded to pod?

**Comment by ppmtscory** [comment]
That's great it's working!  EMV isn't working in the sandbox because of the way that EMV transactions are processed.  It's possible that it *may* work for swipe transactions from the EMV reader in the future but EMV transactions will likely never work in Sandbox.

For your Pod question, that would be something that we'd need to ask @mpavlinsky.  I can follow up with him internally as well and get back to you.

**Comment by mpavlinsky** [comment]
@rleiwang 1.6.1 is now uploaded to the cocoapods repository.

Thanks for bringing this to our attention.
