### ISSUE TITLE
Is PayPal Here development from UK possible?

### ISSUE THREAD

**Issue by brainfuel** [PayPal-Mobile/ios-here-sdk-dist#67]
I'm a little confused. PayPal Here is available in the UK for consumers, however I read on the PayPal developer site : https://developer.paypal.com/docs/integration/paypal-here/

"The PayPal Here SDK currently supports US-based PayPal accounts operating within US borders."

Is this actually correct? To develop an app with PayPal Here integration for the UK market...I have to live in US?

**Comment by ppmtscory** [comment]
@brainfuel the PPH SDK is available in US, UK, and AU currently.  Thank you for bringing this to our attention - I will file the request to update the developer site accordingly.
