### ISSUE TITLE
Card Decryption Error (pay/card_decryption_failure)

### ISSUE THREAD

**Issue by AlexGamezo** [PayPal-Mobile/ios-here-sdk-dist#69]
Hey,

One new issue we're running into is we're getting a Card Decryption Error response from the API when we try to process a card. We're receiving this response regardless of type (Swipe or CHIP). Code 600025

This was working in sandbox before, but isn't any longer. Any pointers on what we may be doing wrong?

**Comment by djMax** [comment]
This is with a chip and pin reader?

**Comment by AlexGamezo** [comment]
Correct, the Bluetooth PayPal Here reader

**Comment by ppmtscory** [comment]
This would have been due to using the EMV reader in the Sandbox environment.  I've also posted this information in your other issue #70.
