### ISSUE TITLE
CHIP Cards Auth/Cap process

### ISSUE THREAD

**Issue by AlexGamezo** [PayPal-Mobile/ios-here-sdk-dist#70]
Is this process supported for CHIP cards? If so, is there an example of this workflow? It appears that the authorizePaymentWithPaymentType method doesn't support the CHIP PaymentType

**Comment by djMax** [comment]
C&p readers don't currently work in sandbox. We're working on getting swipe to work with production readers but emv probably never will

**Comment by AlexGamezo** [comment]
Is this purely for the auth/cap process? Or in general? I have the other open issue (#69) regarding Card Decryption Failure, is that related? If so, how do we test this integration? Using real CC would be highly problematic.

**Comment by ppmtscory** [comment]
@AlexGamezo the readers do not work in Sandbox.  Also, there currently isn't auth/capture capabilities with the EMV readers.  In order to test the integration, yes, you would need to run a couple samples in Production.  Once testing is complete, you would be able to refund your credit card.
