### ISSUE TITLE
Waiting for Signature

### ISSUE THREAD

**Issue by AlexGamezo** [PayPal-Mobile/ios-here-sdk-dist#71]
In attempting to process an EMV transaction, I'm dropped into a state where it's waiting for signature post a call to processPaymentUsingUIWithPaymentType. We currently have an in-app process for getting the Signature, which I'll be able to pass the image data to PayPal, but presently, I'm trying to just test with a blank signature using the following code:

```
CGRect rect = CGRectMake(0, 0, 320, 480);
PPHSignatureView* view = [[PPHSignatureView alloc] initWithFrame:rect];
view.backgroundColor = [UIColor lightGrayColor];
[self.webView.scrollView addSubview:view];

PPHTransactionManager *tm = [PayPalHereSDK sharedTransactionManager];
PPHInvoice *invoice = [tm currentInvoice];
PPHTransactionRecord *transaction = [[PPHTransactionRecord alloc] initWithInvoice:invoice];

[tm provideSignature:[view printableImage] forTransaction:transaction completionHandler:^(PPHError *error) { ; }];
```

This is (of course?) throwing an error due to the transaction not actually being filled out by my code above, and so it can't add the signature to it.

The completion handler of the processPaymentUsingUIWithPaymentType is not being entered at this point beforehand, so I do not have access to the PPHTransactionResponse from that callback.

I'm at a loss. What am I doing wrong and more importantly, what is the correct process?

I'm using the production endpoint, as it was previously stated (and has been my experience) that the sandbox environment doesn't work with the EMV Bluetooth reader. Also, it should be noted that my CC does see these charges being made, and the reversed afterward, so looks like the transaction is being attempted, getting to PayPal, just not being finalized and reversed due to my mishandling of the signature. 

As a side-note, apparently Chase does not like 35 attempted charges of $1 and then reversals, and will block the card as attempted fraud :)

Hoping this is something simple and stupid, please help! :)

**Comment by ppmtscory** [comment]
With EMV, the UI is all handled by the SDK.  This includes the signature screen and the receipt screen.  We handle everything to ensure all EMV requirements are being met so you won't be able to override them at this point.

**Comment by mpavlinsky** [comment]
To add a bit more information: the `provideSignature` API is only supported as part of the non-UI transaction flows. There is no way to add a signature other than the one collected by the UI presented by the SDK for EMV transactions currently.

**Comment by AlexGamezo** [comment]
Thank you both. Seems like I'm just having an issue with providing a valid navigationController then. 

It is very useful to know that signature and receipt is already built in. Are there plans to make this customizable in the future? Presently, we have signature and receipt screens built into our app, with marketing messaging to encourage customers to complete them for CRM info. Also, is there an opportunity to provide default email/phone for text? Would that be something I should pass as part of the initially created invoice?

Again, thanks for the clarification!

**Comment by ppmtscory** [comment]
@AlexGamezo I apologize for the long delay.  The receipt and signature customization options will depend on any flexibility that we get with various EMV restrictions so I can't really say what is/isn't on the road-map for that.  As for prefilling the email or phone, you could play around with [receiptEmailAddress](http://paypal-mobile.github.io/ios-here-sdk-dist/Classes/PPHInvoice.html#//api/name/receiptEmailAddress) and [receiptPhoneNumber](http://paypal-mobile.github.io/ios-here-sdk-dist/Classes/PPHInvoice.html#//api/name/receiptPhoneNumber), as part of the invoice, to see if they give you what you need.
