### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by therunggedmen** [PayPal-Mobile/ios-here-sdk-dist#73]
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <id>tag:github.com,2008:/therunggedmen</id>
  <link type="text/html" rel="alternate" href="https://github.com/therunggedmen"/>
  <link type="application/atom+xml" rel="self" href="https://github.com/therunggedmen.atom"/>
  <title>therunggedmen’s Activity</title>
  <updated>2015-12-27T22:22:57Z</updated>
</feed>

**Comment by therunggedmen** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <id>tag:github.com,2008:/therunggedmen</id>
  <link type="text/html" rel="alternate" href="https://github.com/therunggedmen"/>
  <link type="application/atom+xml" rel="self" href="https://github.com/therunggedmen.atom"/>
  <title>therunggedmen’s Activity</title>
  <updated>2015-12-27T22:22:57Z</updated>
</feed>

**Comment by ppmtscory** [comment]
Closing due to no information in the request.  If you are having an issue, please reopen with detailed information of what's happening.
