### ISSUE TITLE
invoice.payerEmail field cannot be set

### ISSUE THREAD

**Issue by dnbedwards** [PayPal-Mobile/ios-here-sdk-dist#74]
I noticed there was also a closed issue with no solution to this - we're getting the following error when trying to pre-set the email address used for invoicing:

    "The operation couldn’t be completed. (service_error error 600000.) - Unrecognized field \"email\" (Class com.paypal.hereapi.rest.merchant.model.payment.PaymentRequest), not marked as ignorable\n at [Source: org.apache.catalina.connector.CoyoteInputStream@649c9f02; line: 1, column: 71] (through reference chain: com.paypal.hereapi.rest.merchant.model.payment.PaymentRequest[\"email\"])"

In terms of how we're setting the payerEmail field on the invoice, its as follows (in Swift):

    let invoice = PPHInvoice(item: "Test Invoice", forAmount: PPHAmount(decimal: NSDecimalNumber(double: 1.0)))
    invoice.billingInfo.phoneNumber = mobilePhone
    invoice.payerEmail = email
    PayPalHereSDK.sharedTransactionManager().beginPaymentUsingUIWithInvoice(invoice, transactionController: self)

**Comment by ppmtscory** [comment]
Are you simply trying to pre-fill the email address on the receipt screen?  If so, you can use the following... `invoice.receiptEmailAddress = "payeremailtest@test.com"`

**Comment by dnbedwards** [comment]
Yeah should have said I already noticed that. Thanks.
