### ISSUE TITLE
Error when refunding

### ISSUE THREAD

**Issue by brainfuel** [PayPal-Mobile/ios-here-sdk-dist#78]
I obtain the invoice ID from a previous transaction stored in Core Data...

   [PPHInvoice downloadInvoiceForInvoiceId:invoiceId context:nil completionHandler:^ (PPHInvoice *invoice, PPHError *error)

Once I have obtained the PPHInvoice, I call...

  [[PayPalHereSDK sharedTransactionManager] beginRefundUsingUIWithInvoice:invoiceId 
                                                              transactionController:paymentCompleteViewController];

But I get this error every time..

Error Domain=PPHLocal Code=-2012 Refunding a transaction that was paid by "UNKNOWN" requires transactionId to be set on the transaction record. apiMessage=(null) message=(null) correlationId=(null) @ 2016-02-02 03:37:18 +0000

Any ideas?

**Comment by brainfuel** [comment]
I got it working using this method instead..

     PPHTransactionRecord * record  = [[PPHTransactionRecord alloc] initWithTransactionId:transaction.payPalTransactionId];
       
                [[PayPalHereSDK sharedTransactionManager] beginRefund:record  forAmount: nil completionHandler: ^(PPHTransactionResponse *response){

**Comment by ppmtscory** [comment]
There's currently a bug within the SDK for the EMV refund method that you stated in your original inquiry.  This will be fixed with a release soon.
