### ISSUE TITLE
Enter Sandbox mode

### ISSUE THREAD

**Issue by tadeegan** [PayPal-Mobile/ios-here-sdk-dist#82]
How do I enter sandbox mode in the paypal here app.  Ive tried the steps listed here but it simply doesnt work:
https://developer.paypal.com/docs/integration/paypal-here/sandbox-testing/using-the-sandbox-mode-on-the-paypal-mobile-app/

**Comment by djMax** [comment]
We don't have a similar thing in PPH. In the SDK though you can use our stages. Send me an email at m at x.com and I can figure out the best server for you to use and send credentials and such.

**Comment by djMax** [comment]
Are you doing EMV dev or regular mag stripe? EMV in stage requires a special reader unfortunately.

**Comment by tadeegan** [comment]
I am just deep linking into the Pay Pal here app but I need a test account in order to verify that it works correctly.  I keep getting declined for an account.  Very frustrating...

**Comment by ppmtscory** [comment]
Closing as there's no way to set the PayPal Here App to sandbox mode.  The steps listed above were for an older version of the PayPal Consumer app and do not apply to the recent version, nor do they apply to the PayPal Here app.
