### ISSUE TITLE
App rejected due to use of setAllowsAnyHTTPSCertificate:forHost: 

### ISSUE THREAD

**Issue by brainfuel** [PayPal-Mobile/ios-here-sdk-dist#83]
"Your app uses or references the following non-public APIs, which is a violation of the App Store Review Guidelines: setAllowsAnyHTTPSCertificate:forHost:"

Command line strings -a suggests Paypal binary is at fault.

Could you resolve this quick please.

Thanks.

**Comment by djMax** [comment]
You're building with the debug version I believe - we don't have this in the release version which is exactly what's in our shipping app.

**Comment by brainfuel** [comment]
Aha, OK thanks.

**Comment by djMax** [comment]
(if that's not it, let us know and we'll double check the latest binaries)

**Comment by brainfuel** [comment]
Just checked, yes that was the problem. Thanks for your help.
