### ISSUE TITLE
Payment name/email doesn't show up on Account History page

### ISSUE THREAD

**Issue by rleiwang** [PayPal-Mobile/ios-here-sdk-dist#84]
Hi

The payment name/email doesn't show up on transaction history page. Is this something I missed?

![image](https://cloud.githubusercontent.com/assets/6434571/14371122/46150860-fce9-11e5-93b8-8f71fb503846.png)

**Comment by ppmtscory** [comment]
Most of the time when the name/email shows up like this, it's due to either a bad read of the card or a bad track on the card itself.  You'll see this in the Sandbox sometimes when folks will overuse a card and/or keep using a giftcard over and over for testing.
