### ISSUE TITLE
How we get refresh token for long time use ?

### ISSUE THREAD

**Issue by rakesh-ideal** [PayPal-Mobile/ios-here-sdk-dist#86]
I Run the code from PayPal-Mobile/ios-here-sdk-dict, Everything is working fine, but generated token does not seems to refresh token its expiring in 8 hour, so
How i can generate refresh token for iOS app as generating in android sample ?
I checked android app generated refresh token not working with iOS app ?

**Comment by ppmtscory** [comment]
We're looking into this currently.  If needed, you can use the Authentication Listener and then manually update the access token when the `onInvalidToken` method is invoked.  I'll update here once we confirm what's happening with the auto-refreshing of the access token.

**Comment by ppmtscory** [comment]
My apologies for the delay but everything should be working on this front.  If you're seeing anything different, please do let us know.
