### ISSUE TITLE
Non-Paypal Refund and Oauth issue

### ISSUE THREAD

**Issue by vivekadvsol** [PayPal-Mobile/ios-here-sdk-dist#88]
Hi,
I am trying to make a refund using PayPal ( The transaction was not done by paypal previously). I tried to use this ,
```
  [[PayPalHereSDK sharedPaymentProcessor] beginNonPayPalRefundWithInvoiceId:myinvid forAmount:RefundAmount completionHandler:^(PPHPaymentResponse * response) {
                
                [weakSelf gotoPaymentCompleteScreenWithResponse:response];

            }];
```

But i get an exception saying 

> name: @"**UnimplementedBehavior**" - reason: @"**Non-PayPal payments are not yet supported using Oauth**"

So how do I approach this refund? Is there any other way?

**Comment by ppmtscory** [comment]
I'm not aware of any way to refund a non-PayPal payment using this PayPal Here SDK in it's current state.

**Comment by vivekadvsol** [comment]
Thanks @ppmtscory. 

I wonder why there is _"beginNonPayPalRefundWithInvoiceId"_ exist in the sdk. 

We have a scenario where our customer have windows POS and iOS pos. In Windows pos we use bank provided card reader/pin pad and in iOS we use paypal here. 

If a customer done a transaction with bank provided reader @ Windows pos and comes to the iOS pos to do a refund , how can we do this with Paypal? Is there any existing feature with iOS sdk which I don't see?  

Thanks :)

**Comment by ppmtscory** [comment]
Ya, I will need to do some research as to it's origin to know more about what it's availability is.  However, if there was a way to use the same POS system on both Windows and iOS, would that be something that you'd be interested in?

**Comment by vivekadvsol** [comment]
Thanks @ppmtscory :) 

We cannot use the same as our windows POS system is a Microsoft one and we replicated the in iOS. We will find some work around like directing return/refund to Windows POS and use iOS as a pure queue  buster. Thanks for your effort :)
