### ISSUE TITLE
Unable to connect Card Reader

### ISSUE THREAD

**Issue by javagc** [PayPal-Mobile/ios-here-sdk-dist#91]
I have configured my app according to docs/ProjectConfiguration.md , but i can not connect card reader

**PayPalHereSDK.sharedCardReaderManager().activeReader().readerType** is not working for me 

Are there any additional configuration?

Thanks

**Comment by ppmtscory** [comment]
This is most likely due to the active merchant not being set completely.  Whether you're using Live or Sandbox, you'll need to ensure that the merchant account is set completely and is enabled for PayPal Here.  The merchant is set via either `setupWithCredentials` or `setupWithCompositeTokenString`.

**Comment by javagc** [comment]
Thank you for your reply. Here is my code (see attached file) . we have

 configured merchant for PayPal here

`class PayPallViewController: UIViewController,PPHTransactionControllerDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()
        PayPalHereSDK.sharedCardReaderManager().openActiveReader();
//        debugPrint(PayPalHereSDK.sharedCardReaderManager().activeReader().readerType)
        
    }
    
    @IBAction func click(sender: AnyObject) {
        
        PayPalHereSDK.selectEnvironmentWithType(PPHSDKServiceType.ePPHSDKServiceType_Sandbox)

        PayPalHereSDK.setupWithCredentials("A015cNtaBO.V7rvdPdR4o0cgxO6BgwW312la7hj-JiueATdfpcI",
                                           refreshUrl: "http://google.com",
                                           tokenExpiryOrNil: "1245"
        ) { (a:PPHInitResultType, b:PPHError!, c:PPHMerchantInfo!) in
            debugPrint(c.invoiceContactInfo);
            
            var invoice = PPHInvoice(item: "Amount", forAmount: PPHAmount(amount: 23, inCurrency: "USD"));
            PayPalHereSDK.sharedTransactionManager().beginPaymentUsingUIWithInvoice(invoice, transactionController: self);
            PayPalHereSDK.sharedTransactionManager().activateReaderForPayments(nil);
            
        }
     
    }
    
    func userDidSelectRefundMethod(refundOption: PPHPaymentMethod) {
        var a = 90;
    }
    func userDidSelectPaymentMethod(paymentOption: PPHPaymentMethod) {
         var a = 90;
    }
    
    func getCurrentNavigationController() -> UINavigationController! {
        return self.navigationController;
    }
}
`

**Comment by ppmtscory** [comment]
I get an invalid access token error... can you refresh that and let me know?

**Comment by javagc** [comment]
sorry my late response, A015rwH4tYFbvdip3XViwtcOrTjHEzwv4tbD52nZHDxyxrs there is new token

**Comment by ppmtscory** [comment]
I'm seeing a scope error so therefore your merchant is not getting completely set up.  That access token comes up with a test-passenger@ email address.  Is that the account you want receiving the funds?  Whichever account you want to receive the funds, that's the account that you need to 'onboard' with the right scopes to get the refresh token to then turn into an access token.  Perhaps if you let me know how you're generating the refresh token for your merchant/receiving account, then we can get you going from there.  More information on that process can be found in the Merchant Onboarding Guide that's in the docs folder of this repo.

**Comment by lomso** [comment]
@ppmtscory thanks so much for your help. I'm a teammate of @javagc. They way we have been generating refresh tokens was appropriate for newly onboarded merchants (as described here ). However, we ourselves have a merchant account with PayPal Here and Login with PayPal services enabled. So, we have the Client ID and Secret, but we are unclear about how to get the Authorization Code from PayPal. As we understand, one needs the Client ID and the Authorization Code in order to obtain the long-lived refresh token and access token.

**Comment by ppmtscory** [comment]
You can simply send your own account through the onboarding flow.  Just login with your own account and then you'll get the respective auth code from the onboarding flow for which you can turn into the refresh token to store for your own account.  Essentially you treat your own account just like a merchant account.

**Comment by lomso** [comment]
Thanks. So we were doing it that way too but were unable to activate the Swiper. Could you please check if the following Access token is valid:
A015.1kmtDrBFPF1dTX1AS0Nou8AFPyZYg9xZafSRNOdQJQ

**Comment by ppmtscory** [comment]
That access token is expired.  What errors are you seeing in the console logs when attempting to initialize the merchant account via `setupWithCredentials`?

**Comment by javagc** [comment]
So, I am testing on Android now, my code is here 

` PayPalHereSDK.init(this, PayPalHereSDK.Sandbox);

        Credentials credentials = new OAuthCredentials("A0151.bD53RwYRRn7wDWgyw4P5g2UGwbW5GrZNx7PZOxS24");

        PayPalHereSDK.setCredentials(credentials, new DefaultResponseHandler<Merchant, PPError<MerchantManager.MerchantErrors>>() {
            @Override
            public void onSuccess(Merchant merchant) {
                List<CardReaderManager.CardReader> availableCardReaders = PayPalHereSDK.getCardReaderManager().getAvailableReaders();
            }

            @Override
            public void onError(PPError<MerchantManager.MerchantErrors> merchantErrorsPPError) {
            }
        });`

and device  is connected to the device.  `getAvailableReaders()` return 0.  

p.s we are sure that our merchant account enabled for PayPal Here

**Comment by ppmtscory** [comment]
What is showing in logcat?

**Comment by javagc** [comment]
![1](https://cloud.githubusercontent.com/assets/3741282/16920938/a4c26b14-4d20-11e6-8b05-4e726a4bfb82.png)


p.s new token is A015CCY4S7sZEPl60GTolAqvyBhSVYqArg--kAByu4-Kw58

**Comment by ppmtscory** [comment]
@javagc that merchant account you were using didn't have PayPal Here enabled on it for sandbox.  I went ahead and manually toggled it on for you and ran a test payment through.  If you're merchant account isn't fully initialized, then the reader interactions will not work correctly.

**Comment by lomso** [comment]
@ppmtscory After making sure the merchant was enabled for Here services in both Sandbox and Live, we have resolved this issue. We managed to connect with the card reader. Thank you for your help!

**Comment by ppmtscory** [comment]
@lomso thank you for the update.  I will close this now.
