### ISSUE TITLE
Missing field: merchantInfo.businessName (ERROR 580029)

### ISSUE THREAD

**Issue by lomso** [PayPal-Mobile/ios-here-sdk-dist#93]
We are trying to process real payments using a credit card swiper and are getting a following error:
Missing field: merchantInfo.businessName 
(see the attached screenshot) 

![2016-07-23](https://cloud.githubusercontent.com/assets/5263690/17080523/de385184-50f8-11e6-959c-e9c8f4ff6cfd.png)

I looked up the business name in the merchant's PayPal account that we are using for the testing and the business name is there. When generating tokens for this merchant, we used following scopes:

`       scopelist.Add("https://uri.paypal.com/services/paypalhere");
       scopelist.Add("email");
       scopelist.Add("address");
       scopelist.Add("https://uri.paypal.com/services/paypalattributes/business");`

We need help to find what we are missing. Really appreciate your help.

**Comment by ppmtscory** [comment]
Can you remove all tokens for the merchant and try to reconnect them?  Those scopes are good but, for some reason, your access token looks funky.  Also, make sure that you aren't trying to run the payment until after your merchant is fully initialized.  If you don't get the merchant fully initialized, this can happen.

**Comment by lomso** [comment]
@ppmtscory Thanks for the prompt response. I just wanna make sure I'm not missing a step, by initializing, you mean from the client (mobile app) or from the intermediary server (our backend)?

**Comment by ppmtscory** [comment]
I'm talking in the client - more specifically, either the `setupWithCredentials` method or the `setupWithCompositeToken` method.  This is what initializes the merchant and you need to wait for this success prior to running a payment.  During this initialization, the SDK is grabbing information about the merchant account based on the scopes that you were granted.

**Comment by lomso** [comment]
I think it was your suggestion that our tokens looked funky that helped. We successfully managed to process payments. Thank you so much for your help.

**Comment by ppmtscory** [comment]
That's great, thank you for the update!
