### ISSUE TITLE
PPH SDK 1.6.6, iOS, Unregistered Account error 60006

### ISSUE THREAD

**Issue by ngoctr** [PayPal-Mobile/ios-here-sdk-dist#95]
Hi, I got this error (in a Sandbox env) when trying to make a payment (with the TakePayment sample app):
{
  "title" : "PPH_EMVSDK_Error",
  "message" : "The operation couldn’t be completed. (pay\/unregistered_account error 600006.) - Unregistered Account",
  "buttons" : [
    "PPH_EMVSDK_OKLabel"
  ]
}

Is there anything I can do to fix this? Is this possible to test Payment and Refund with PPH in a sandbox environment?

**Comment by ppmtscory** [comment]
This error will come up when the account you're using to receive funds isn't enabled for PayPal Here or the email address isn't confirmed on the account.  For getting a sandbox merchant account, login at developer.paypal.com, go to the dashboard, click sandbox accounts on the left menu, click to create a new account, and create a US business account with the first name of Ryan.  Then you can login at www.sandbox.paypal.com/signup-pph to enable PayPal Here on the account.  Once you get to the 'order a reader' screen, then you can close out and the account should be able to be used with the TakePayment app.

**Comment by ngoctr** [comment]
Thanks for the prompt response @ppmtscory. Following the guide and the problem resolved. Thanks.
