### ISSUE TITLE
Processing payment without using PPH's UI + Timeout issue (SDK 1.6.6)

### ISSUE THREAD

**Issue by ngoctr** [PayPal-Mobile/ios-here-sdk-dist#96]
We tried to process a payment use the following flow:

1. Setup the invoice and add item, then call:
`[[PayPalHereSDK sharedTransactionManager]
      beginPaymentUsingUIWithInvoice:self.invoice
               transactionController:self];`
2. In  `- (void)userDidSelectPaymentMethod:(PPHPaymentMethod)paymentOption` we called `[[PayPalHereSDK sharedTransactionManager]
      processPaymentWithPaymentType:` instead of `[[PayPalHereSDK sharedTransactionManager]
      processPaymentUsingUIWithPaymentType:`, the transaction was successfully processed (no error in the completion callback), however the payment Information such as transactionId and merchantReferenceNumber were empty).

Question 1: Can we process payment without using the SDK's built-inUI? If yes, how can we do that? Is above the correct way?
Question 2: We would like to know how to intercept the timeout event for a contactless payment, but it seems there is not a way to handle the timeout event. We implemented `(void)readerDidDeactivateForPayments` from PPHTransactionControllerDelegate but that didn't get called.

Thanks.

**Comment by ppmtscory** [comment]
You don't have to use the UI if you are NOT using the EMV reader.  If you are using the EMV reader, then you have to use the UI as part of our EMV certifications.  For getting the contactless timeout, you'd utilize [`contactlessTimeoutAction`](http://paypal-mobile.github.io/ios-here-sdk-dist/Protocols/PPHTransactionControllerDelegate.html#//api/name/contactlessTimeoutAction) via the `PPHTransactionControllerDelgate`.
